
import React from 'react';
import { Link } from 'react-router-dom';

const AboutSmartLearn: React.FC = () => {
  return (
    <div className="min-h-screen bg-white text-gray-900 font-sans selection:bg-blue-100 selection:text-blue-700">
      <div className="max-w-4xl mx-auto px-6 py-20">
        <nav className="mb-12">
          <Link to="/" className="text-blue-600 hover:text-blue-700 font-medium flex items-center gap-2 group transition-all">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 transform group-hover:-translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Home
          </Link>
        </nav>

        <header className="mb-16">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight text-gray-900 mb-6">
            About <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-indigo-600">SmartLearn AI</span>
          </h1>
          <p className="text-xl text-gray-600 leading-relaxed max-w-2xl">
            Empowering the next generation of students with AI-driven educational tools designed for excellence.
          </p>
        </header>

        <section className="prose prose-blue prose-lg max-w-none">
          <p className="mb-6">
            <strong>SmartLearn AI</strong> is a revolutionary AI-powered learning platform designed to bridge the gap between students and teachers. In today's fast-paced educational landscape, SmartLearn AI provides the essential tools needed for personalized and efficient learning.
          </p>

          <h2 className="text-2xl font-bold mt-12 mb-4">Why Choose SmartLearn AI?</h2>
          <p className="mb-6">
            Our platform, <strong>SmartLearn AI</strong>, leverages cutting-edge artificial intelligence to offer a comprehensive suite of features. Whether you are preparing for exams or need help with daily studies, SmartLearn AI is your ultimate companion.
          </p>

          <ul className="grid grid-cols-1 md:grid-cols-2 gap-6 list-none p-0">
            <li className="bg-gray-50 p-6 rounded-2xl border border-gray-100">
              <h3 className="text-lg font-semibold mb-2">AI-Powered Quizzes</h3>
              <p className="text-gray-600 text-sm">Interactive quizzes generated by SmartLearn AI to test your knowledge in real-time.</p>
            </li>
            <li className="bg-gray-50 p-6 rounded-2xl border border-gray-100">
              <h3 className="text-lg font-semibold mb-2">Smart Study Planning</h3>
              <p className="text-gray-600 text-sm">Let SmartLearn AI organize your schedule based on your learning pace and goals.</p>
            </li>
            <li className="bg-gray-50 p-6 rounded-2xl border border-gray-100">
              <h3 className="text-lg font-semibold mb-2">Advanced Doubt Solving</h3>
              <p className="text-gray-600 text-sm">Instant answers to complex questions through the SmartLearn AI doubt solver.</p>
            </li>
            <li className="bg-gray-50 p-6 rounded-2xl border border-gray-100">
              <h3 className="text-lg font-semibold mb-2">Exam Management</h3>
              <p className="text-gray-600 text-sm">Comprehensive exam assessment tools for teachers and students via SmartLearn AI.</p>
            </li>
          </ul>

          <h2 className="text-2xl font-bold mt-12 mb-4">Our Vision</h2>
          <p className="mb-6">
            At <strong>SmartLearn AI</strong>, we believe that education should be accessible and adaptive. By integrating SmartLearn AI into the classroom, we empower teachers to provide better feedback and students to achieve higher goals. <strong>SmartLearn AI</strong> is more than just a tool; it's a movement towards smarter education.
          </p>

          <p>
            Join thousands of students and educators who are already using <strong>SmartLearn AI</strong> to transform their educational experience. Experience the future of learning with <strong>SmartLearn AI</strong> today.
          </p>
        </section>

        <footer className="mt-20 pt-8 border-t border-gray-100 text-center">
          <p className="text-gray-500 text-sm">
            &copy; {new Date().getFullYear()} SmartLearn AI. All rights reserved.
          </p>
        </footer>
      </div>
    </div>
  );
};

export default AboutSmartLearn;
